# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/user/soc/Zedboard/lab3/lab3.cache/wt [current_project]
set_property parent.project_path /home/user/soc/Zedboard/lab3/lab3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/user/soc/Zedboard/ip_repo/S00_AXI_1.0 [current_project]
add_files /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/led_test_system.bd
set_property used_in_implementation false [get_files -all /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/ip/led_test_system_processing_system7_0_0/led_test_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/ip/led_test_system_rst_processing_system7_0_100M_0/led_test_system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/ip/led_test_system_rst_processing_system7_0_100M_0/led_test_system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/ip/led_test_system_rst_processing_system7_0_100M_0/led_test_system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/ip/led_test_system_auto_pc_0/led_test_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/led_test_system_ooc.xdc]
set_property is_locked true [get_files /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/led_test_system.bd]

read_vhdl -library xil_defaultlib /home/user/soc/Zedboard/lab3/lab3.srcs/sources_1/bd/led_test_system/hdl/led_test_system_wrapper.vhd
read_xdc /home/user/soc/Zedboard/lab3/lab3.srcs/constrs_1/new/led_constraints.xdc
set_property used_in_implementation false [get_files /home/user/soc/Zedboard/lab3/lab3.srcs/constrs_1/new/led_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top led_test_system_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef led_test_system_wrapper.dcp
catch { report_utilization -file led_test_system_wrapper_utilization_synth.rpt -pb led_test_system_wrapper_utilization_synth.pb }
